export const NEWS_SOURCES = {
  "abc-news": "ABC News",
  "abc-news-au": "ABC News (AU)",
  "ars-technica": "Ars Technica",
  "associated-press": "Associated Press",
  axios: "Axios",
  "bbc-news": "BBC News",
  "bbc-sport": "BBC Sport",
  bloomberg: "Bloomberg",
  "business-insider": "Business Insider",
  "cbc-news": "CBC News",
  "cbs-news": "CBS News",
  cnn: "CNN",
  engadget: "Engadget",
  "nbc-news": "NBC News",
  espn: "ESPN",
  "financial-post": "Financial Post",
  fortune: "Fortune",
  "fox-sports": "Fox Sports",
  ign: "IGN",
  msnbc: "MSNBC",
  "mtv-news": "MTV News",
  "national-geographic": "National Geographic",
  "new-scientist": "New Scientist",
  newsweek: "Newsweek",
  "new-york-magazine": "New York Magazine",
  "next-big-future": "Next Big Future",
  "nfl-news": "NFL News",
  "nhl-news": "NHL News",
  politico: "Politico",
  recode: "Recode",
  reuters: "Reuters",
  techcrunch: "Tech Crunch",
  "the-globe-and-mail": "The Globe and Mail",
  "the-hill": "The Hill",
  "the-irish-times": "The Irish Times",
  "the-times-of-india": "The Times of India",
  "the-verge": "The Verge",
  "the-wall-street-journal": "The Wall Street Journal",
  "the-washington-post": "The Washington Post",
  time: "Time",
  "usa-today": "USA Today",
  "vice-news": "Vice",
  wired: "Wired",
};
